name: Update Google Scholar Citation Badge

on:
  schedule:
    # Runs at 8:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install the GSBG tool
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gsbg

      # 4. Run your Python script
      - name: Run script to generate badge
        run: python scripts/gene_google_scholar_badges.py

      # 5. Commit the new/updated badge file back to your repository
      - name: Commit and push if badge changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update Google Scholar citation badge"
          file_pattern: "badges/*.svg"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
